# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['server/main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('web/*', 'web'),
        ('web', 'web'),
        ('requirements.txt', '.'),
        ('README.md', '.'),
    ],
    hiddenimports=[
        'eel',
        'psutil',
        'tkinter',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'json',
        'pathlib',
        'zipfile',
        'shutil',
        'configparser',
        'subprocess',
        'threading',
        'queue',
        'time',
        'platform',
        're',
        'os',
        'struct',
        'unicodedata',
        'tempfile',
        'locale',
        'codecs',
        'io',
        'webbrowser',
        'socket',
        'urllib',
        'urllib.parse',
        'urllib.request',
        'http',
        'http.server',
        'socketserver',
        'bottle',
        'gevent',
        'gevent.pywsgi',
        'whichcraft',
        'pkg_resources'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='MinecraftBedrockPanel',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    cofile_version=None,
    version='version_info.txt' if os.path.exists('version_info.txt') else None,
    icon='icon.ico' if os.path.exists('icon.ico') else None,
)
